### ISSUE TITLE
[Feature] section folding for fasta

### ISSUE THREAD

**Issue by jayagami** [Zuttergutao/gmxhelper#1]
Hi, Thanks for your great work.
Currently I am using vscode plugins.
I wondering if there is possibility to add section folding for fasta fomat files.

**Comment by Zuttergutao** [comment]
Sure, I will update it! Thank you for your advise.

**Comment by Zuttergutao** [comment]
The new version v1.0.10 has been released. Now the extension supports the section folding not including the `fasta` format, but also `top` `itp` `mol2` file formats. You can download it from the vscode extension market or download from the github.

**Comment by jayagami** [comment]
Thank you for your reply, I didn't expect you to add this feature in just one day.👀
Thank you for your great work.
