### ISSUE TITLE
overwrites default theme

### ISSUE THREAD

**Issue by slizabeth** [Zuttergutao/gmxhelper#2]
Type: <b>Bug</b>

This extension overwrites every attempt to change display theme

Extension version: 1.0.11
VS Code version: Code 1.74.3 (Universal) (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:07:18.579Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.85GB free)|
|Process Argv|--crash-reporter-id 18cfd67c-5207-43fa-a522-41ca5fac1d73|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1:30587005
3biah626:30602489
f6dab269:30613381
pythonsymbol12cf:30657549

```

</details>

**Comment by Zuttergutao** [comment]
Thank you for your use. 
I'm sorry that this bug is because I customized the theme color. 
I will try to fix it in the next version

**Comment by Zuttergutao** [comment]
> Type: Bug
> 
> This extension overwrites every attempt to change display theme
> 
> Extension version: 1.0.11 VS Code version: Code 1.74.3 (Universal) (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:07:18.579Z) OS version: Darwin arm64 22.1.0 Modes: Sandboxed: No
> 
> System Info
> A/B Experiments

Hi, I think this version (v1.0.12) does not change the display theme when viewing different files. The solution is to write the marker colors into your own settings.json. Thank you for your use and I look forward to your feedback.
